In [91]:
import pandas as pd

In [148]:
# carregando dataframe
dt = pd.read_csv('pokedex_(update_05.20).csv')
dt

,Unnamed: 0,pokedex_number,name,german_name,japanese_name,generation,status,species,type_number,type_1,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,0,1,Bulbasaur,Bisasam,フシギダネ (Fushigidane),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5
1,1,2,Ivysaur,Bisaknosp,フシギソウ (Fushigisou),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5
2,2,3,Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5
3,3,3,Mega Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5
4,4,4,Charmander,Glumanda,ヒトカゲ (Hitokage),1,Normal,Lizard Pokémon,1,Fire,...,2.0,1.0,1.0,0.50,2.00,1.0,1.0,1.0,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1023,1023,888,Zacian Hero of Many Battles,NaN,NaN,8,Legendary,Warrior Pokémon,1,Fairy,...,1.0,1.0,1.0,0.50,1.00,1.0,0.0,0.5,2.0,1.0
1024,1024,889,Zamazenta Crowned Shield,NaN,NaN,8,Legendary,Warrior Pokémon,2,Fighting,...,2.0,1.0,1.0,0.25,0.25,1.0,0.5,0.5,0.5,1.0
1025,1025,889,Zamazenta Hero of Many Battles,NaN,NaN,8,Legendary,Warrior Pokémon,1,Fighting,...,1.0,2.0,2.0,0.50,0.50,1.0,1.0,0.5,1.0,2.0
1026,1026,890,Eternatus,NaN,NaN,8,Legendary,Gigantic Pokémon,2,Poison,...,2.0,1.0,2.0,0.50,1.00,1.0,2.0,1.0,1.0,1.0
1027,1027,890,Eternatus Eternamax,NaN,NaN,8,Legendary,Gigantic Pokémon,2,Poison,...,2.0,1.0,2.0,0.50,1.00,1.0,2.0,1.0,1.0,1.0

In [150]:
# Remoção de duplicatas
dt.duplicated().any()

# O DataFrame não possui valores duplicados!

np.False_

In [151]:
# exibindo colunas existentes para melhor visualização
dt.columns

Index(['Unnamed: 0', 'pokedex_number', 'name', 'german_name', 'japanese_name',
       'generation', 'status', 'species', 'type_number', 'type_1', 'type_2',
       'height_m', 'weight_kg', 'abilities_number', 'ability_1', 'ability_2',
       'ability_hidden', 'total_points', 'hp', 'attack', 'defense',
       'sp_attack', 'sp_defense', 'speed', 'catch_rate', 'base_friendship',
       'base_experience', 'growth_rate', 'egg_type_number', 'egg_type_1',
       'egg_type_2', 'percentage_male', 'egg_cycles', 'against_normal',
       'against_fire', 'against_water', 'against_electric', 'against_grass',
       'against_ice', 'against_fight', 'against_poison', 'against_ground',
       'against_flying', 'against_psychic', 'against_bug', 'against_rock',
       'against_ghost', 'against_dragon', 'against_dark', 'against_steel',
       'against_fairy'],
      dtype='object')

In [152]:
# Remover colunas irrelevantes
dt = dt.loc[:,['pokedex_number','name', 'status', 'species', 'type_1', 'type_2', 'height_m', 'weight_kg', 'hp', 'attack', 'defense', 'speed', ]]
dt

,pokedex_number,name,status,species,type_1,type_2,height_m,weight_kg,hp,attack,defense,speed
0,1,Bulbasaur,Normal,Seed Pokémon,Grass,Poison,0.7,6.9,45.0,49.0,49.0,45.0
1,2,Ivysaur,Normal,Seed Pokémon,Grass,Poison,1.0,13.0,60.0,62.0,63.0,60.0
2,3,Venusaur,Normal,Seed Pokémon,Grass,Poison,2.0,100.0,80.0,82.0,83.0,80.0
3,3,Mega Venusaur,Normal,Seed Pokémon,Grass,Poison,2.4,155.5,80.0,100.0,123.0,80.0
4,4,Charmander,Normal,Lizard Pokémon,Fire,NaN,0.6,8.5,39.0,52.0,43.0,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1023,888,Zacian Hero of Many Battles,Legendary,Warrior Pokémon,Fairy,NaN,2.8,110.0,92.0,130.0,115.0,138.0
1024,889,Zamazenta Crowned Shield,Legendary,Warrior Pokémon,Fighting,Steel,2.9,785.0,92.0,130.0,145.0,128.0
1025,889,Zamazenta Hero of Many Battles,Legendary,Warrior Pokémon,Fighting,NaN,2.9,210.0,92.0,130.0,115.0,138.0
1026,890,Eternatus,Legendary,Gigantic Pokémon,Poison,Dragon,20.0,950.0,140.0,85.0,95.0,130.0
1027,890,Eternatus Eternamax,Legendary,Gigantic Pokémon,Poison,Dragon,100.0,NaN,255.0,115.0,250.0,130.0

In [183]:
# tratar valores ausentes
dt.isnull().sum()

# coluna type_2 e coluna weight_kg possui valores ausentes

pokedex_number    0
name              0
status            0
species           0
type_1            0
type_2            0
height_m          0
weight_kg         0
hp                0
attack            0
defense           0
speed             0
dtype: int64

In [178]:
# Excluindo valores nulos presentes no DataFrame
dt = dt.dropna()
dt

,pokedex_number,name,status,species,type_1,type_2,height_m,weight_kg,hp,attack,defense,speed
0,1,Bulbasaur,Normal,Seed Pokémon,Grass,Poison,0.7,6.9,45.0,49.0,49.0,45.0
1,2,Ivysaur,Normal,Seed Pokémon,Grass,Poison,1.0,13.0,60.0,62.0,63.0,60.0
2,3,Venusaur,Normal,Seed Pokémon,Grass,Poison,2.0,100.0,80.0,82.0,83.0,80.0
3,3,Mega Venusaur,Normal,Seed Pokémon,Grass,Poison,2.4,155.5,80.0,100.0,123.0,80.0
6,6,Charizard,Normal,Flame Pokémon,Fire,Flying,1.7,90.5,78.0,84.0,78.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1020,886,Drakloak,Normal,Caretaker Pokémon,Dragon,Ghost,1.4,11.0,68.0,80.0,50.0,102.0
1021,887,Dragapult,Normal,Stealth Pokémon,Dragon,Ghost,3.0,50.0,88.0,120.0,75.0,142.0
1022,888,Zacian Crowned Sword,Legendary,Warrior Pokémon,Fairy,Steel,2.8,355.0,92.0,170.0,115.0,148.0
1024,889,Zamazenta Crowned Shield,Legendary,Warrior Pokémon,Fighting,Steel,2.9,785.0,92.0,130.0,145.0,128.0
1026,890,Eternatus,Legendary,Gigantic Pokémon,Poison,Dragon,20.0,950.0,140.0,85.0,95.0,130.0

In [184]:
# verificando se os valores ausentes foram deletados
dt.isnull().sum()

pokedex_number    0
name              0
status            0
species           0
type_1            0
type_2            0
height_m          0
weight_kg         0
hp                0
attack            0
defense           0
speed             0
dtype: int64

In [217]:
# Filtrar pokemons proibidos que sejam das categorias:
# Lendários e sub-lendários
# míticos
# pokémon com mega evolução

df = dt[~dt['status'].isin(['Legendary', 'Semi Legendary']) & ~dt['name'].str.contains('mega', case=False)]
df

# Dataframe finalizado

,pokedex_number,name,status,species,type_1,type_2,height_m,weight_kg,hp,attack,defense,speed
0,1,Bulbasaur,Normal,Seed Pokémon,Grass,Poison,0.7,6.9,45.0,49.0,49.0,45.0
1,2,Ivysaur,Normal,Seed Pokémon,Grass,Poison,1.0,13.0,60.0,62.0,63.0,60.0
2,3,Venusaur,Normal,Seed Pokémon,Grass,Poison,2.0,100.0,80.0,82.0,83.0,80.0
6,6,Charizard,Normal,Flame Pokémon,Fire,Flying,1.7,90.5,78.0,84.0,78.0,100.0
15,12,Butterfree,Normal,Butterfly Pokémon,Bug,Flying,1.1,32.0,60.0,45.0,50.0,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1017,883,Arctovish,Normal,Fossil Pokémon,Water,Ice,2.0,175.0,90.0,90.0,100.0,55.0
1018,884,Duraludon,Normal,Alloy Pokémon,Steel,Dragon,1.8,40.0,70.0,95.0,115.0,85.0
1019,885,Dreepy,Normal,Lingering Pokémon,Dragon,Ghost,0.5,2.0,28.0,60.0,30.0,82.0
1020,886,Drakloak,Normal,Caretaker Pokémon,Dragon,Ghost,1.4,11.0,68.0,80.0,50.0,102.0
1021,887,Dragapult,Normal,Stealth Pokémon,Dragon,Ghost,3.0,50.0,88.0,120.0,75.0,142.0