In [1]:
pip install pandas

Requirement already satisfied: pandas in /opt/miniconda3/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/miniconda3/lib/python3.12/site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/miniconda3/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/miniconda3/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
import pandas as pd

In [86]:
dt = pd.read_csv('pokedex_(update_05.20).csv')
dt.info()
dt.fillna(0, inplace=True)
dt.isnull().sum()

# analisar valores discrepantes, outliers presentes no dataframe e trata-los conforme

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028 entries, 0 to 1027
Data columns (total 51 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1028 non-null   int64
 1   pokedex_number    1028 non-null   int64
 2   name              1028 non-null   object
 3   german_name       938 non-null    object
 4   japanese_name     938 non-null    object
 5   generation        1028 non-null   int64
 6   status            1028 non-null   object
 7   species           1028 non-null   object
 8   type_number       1028 non-null   int64
 9   type_1            1028 non-null   object
 10  type_2            542 non-null    object
 11  height_m          1028 non-null   float64
 12  weight_kg         1027 non-null   float64
 13  abilities_number  1028 non-null   int64
 14  ability_1         1025 non-null   object
 15  ability_2         513 non-null    object
 16  ability_hidden    810 non-null    object
 17  total_points      1028 non-null   float64
 18  hp                1028 non-null   float64
 19  attack            1028 non-null   float64
 20  defense           1028 non-null   float64
 21  sp_attack         1028 non-null   float64
 22  sp_defense        1028 non-null   float64
 23  speed             1028 non-null   float64
 24  catch_rate        924 non-null    float64
 25  base_friendship   924 non-null    float64
 26  base_experience   924 non-null    float64
 27  growth_rate       1027 non-null   object
 28  egg_type_number   1028 non-null   int64
 29  egg_type_1        1025 non-null   object
 30  egg_type_2        282 non-null    object
 31  percentage_male   792 non-null    float64
 32  egg_cycles        1027 non-null   float64
 33  against_normal    1028 non-null   float64
 34  against_fire      1028 non-null   float64
 35  against_water     1028 non-null   float64
 36  against_electric  1028 non-null   float64
 37  against_grass     1028 non-null   float64
 38  against_ice       1028 non-null   float64
 39  against_fight     1028 non-null   float64
 40  against_poison    1028 non-null   float64
 41  against_ground    1028 non-null   float64
 42  against_flying    1028 non-null   float64
 43  against_psychic   1028 non-null   float64
 44  against_bug       1028 non-null   float64
 45  against_rock      1028 non-null   float64
 46  against_ghost     1028 non-null   float64
 47  against_dragon    1028 non-null   float64
 48  against_dark      1028 non-null   float64
 49  against_steel     1028 non-null   float64
 50  against_fairy     1028 non-null   float64
dtypes: float64(32), int64(6), object(13)
memory usage: 409.7+ KB

Unnamed: 0          0
pokedex_number      0
name                0
german_name         0
japanese_name       0
generation          0
status              0
species             0
type_number         0
type_1              0
type_2              0
height_m            0
weight_kg           0
abilities_number    0
ability_1           0
ability_2           0
ability_hidden      0
total_points        0
hp                  0
attack              0
defense             0
sp_attack           0
sp_defense          0
speed               0
catch_rate          0
base_friendship     0
base_experience     0
growth_rate         0
egg_type_number     0
egg_type_1          0
egg_type_2          0
percentage_male     0
egg_cycles          0
against_normal      0
against_fire        0
against_water       0
against_electric    0
against_grass       0
against_ice         0
against_fight       0
against_poison      0
against_ground      0
against_flying      0
against_psychic     0
against_bug         0
against_rock        0
against_ghost       0
against_dragon      0
against_dark        0
against_steel       0
against_fairy       0
dtype: int64

In [77]:
# Remoção de duplicatas
dt.drop_duplicates()

,pokedex_number,name,status,species,type_1,type_2,height_m,weight_kg,hp,attack,defense,speed
0,1,Bulbasaur,Normal,Seed Pokémon,Grass,Poison,0.7,6.9,45.0,49.0,49.0,45.0
1,2,Ivysaur,Normal,Seed Pokémon,Grass,Poison,1.0,13.0,60.0,62.0,63.0,60.0
2,3,Venusaur,Normal,Seed Pokémon,Grass,Poison,2.0,100.0,80.0,82.0,83.0,80.0
3,3,Mega Venusaur,Normal,Seed Pokémon,Grass,Poison,2.4,155.5,80.0,100.0,123.0,80.0
4,4,Charmander,Normal,Lizard Pokémon,Fire,NaN,0.6,8.5,39.0,52.0,43.0,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1023,888,Zacian Hero of Many Battles,Legendary,Warrior Pokémon,Fairy,NaN,2.8,110.0,92.0,130.0,115.0,138.0
1024,889,Zamazenta Crowned Shield,Legendary,Warrior Pokémon,Fighting,Steel,2.9,785.0,92.0,130.0,145.0,128.0
1025,889,Zamazenta Hero of Many Battles,Legendary,Warrior Pokémon,Fighting,NaN,2.9,210.0,92.0,130.0,115.0,138.0
1026,890,Eternatus,Legendary,Gigantic Pokémon,Poison,Dragon,20.0,950.0,140.0,85.0,95.0,130.0
1027,890,Eternatus Eternamax,Legendary,Gigantic Pokémon,Poison,Dragon,100.0,NaN,255.0,115.0,250.0,130.0

In [54]:
# exibindo colunas existentes
dt.columns

Index(['Unnamed: 0', 'pokedex_number', 'name', 'german_name', 'japanese_name',
       'generation', 'status', 'species', 'type_number', 'type_1', 'type_2',
       'height_m', 'weight_kg', 'abilities_number', 'ability_1', 'ability_2',
       'ability_hidden', 'total_points', 'hp', 'attack', 'defense',
       'sp_attack', 'sp_defense', 'speed', 'catch_rate', 'base_friendship',
       'base_experience', 'growth_rate', 'egg_type_number', 'egg_type_1',
       'egg_type_2', 'percentage_male', 'egg_cycles', 'against_normal',
       'against_fire', 'against_water', 'against_electric', 'against_grass',
       'against_ice', 'against_fight', 'against_poison', 'against_ground',
       'against_flying', 'against_psychic', 'against_bug', 'against_rock',
       'against_ghost', 'against_dragon', 'against_dark', 'against_steel',
       'against_fairy'],
      dtype='object')

In [68]:
# Remover colunas irrelevantes
dt = df.loc[:,['pokedex_number','name', 'status', 'species', 'type_1', 'type_2', 'height_m', 'weight_kg', 'hp', 'attack', 'defense', 'speed', ]]
dt

,pokedex_number,name,status,species,type_1,type_2,height_m,weight_kg,hp,attack,defense,speed
0,1,Bulbasaur,Normal,Seed Pokémon,Grass,Poison,0.7,6.9,45.0,49.0,49.0,45.0
1,2,Ivysaur,Normal,Seed Pokémon,Grass,Poison,1.0,13.0,60.0,62.0,63.0,60.0
2,3,Venusaur,Normal,Seed Pokémon,Grass,Poison,2.0,100.0,80.0,82.0,83.0,80.0
3,3,Mega Venusaur,Normal,Seed Pokémon,Grass,Poison,2.4,155.5,80.0,100.0,123.0,80.0
4,4,Charmander,Normal,Lizard Pokémon,Fire,NaN,0.6,8.5,39.0,52.0,43.0,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1023,888,Zacian Hero of Many Battles,Legendary,Warrior Pokémon,Fairy,NaN,2.8,110.0,92.0,130.0,115.0,138.0
1024,889,Zamazenta Crowned Shield,Legendary,Warrior Pokémon,Fighting,Steel,2.9,785.0,92.0,130.0,145.0,128.0
1025,889,Zamazenta Hero of Many Battles,Legendary,Warrior Pokémon,Fighting,NaN,2.9,210.0,92.0,130.0,115.0,138.0
1026,890,Eternatus,Legendary,Gigantic Pokémon,Poison,Dragon,20.0,950.0,140.0,85.0,95.0,130.0
1027,890,Eternatus Eternamax,Legendary,Gigantic Pokémon,Poison,Dragon,100.0,NaN,255.0,115.0,250.0,130.0

In [71]:
# ratar valores ausentes: Identifique valores nulos ou ausentes e aplique as ações necessárias para corrigi-los (preenchimento ou remoção).
dt.dropna()

,pokedex_number,name,status,species,type_1,type_2,height_m,weight_kg,hp,attack,defense,speed
0,1,Bulbasaur,Normal,Seed Pokémon,Grass,Poison,0.7,6.9,45.0,49.0,49.0,45.0
1,2,Ivysaur,Normal,Seed Pokémon,Grass,Poison,1.0,13.0,60.0,62.0,63.0,60.0
2,3,Venusaur,Normal,Seed Pokémon,Grass,Poison,2.0,100.0,80.0,82.0,83.0,80.0
3,3,Mega Venusaur,Normal,Seed Pokémon,Grass,Poison,2.4,155.5,80.0,100.0,123.0,80.0
6,6,Charizard,Normal,Flame Pokémon,Fire,Flying,1.7,90.5,78.0,84.0,78.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1020,886,Drakloak,Normal,Caretaker Pokémon,Dragon,Ghost,1.4,11.0,68.0,80.0,50.0,102.0
1021,887,Dragapult,Normal,Stealth Pokémon,Dragon,Ghost,3.0,50.0,88.0,120.0,75.0,142.0
1022,888,Zacian Crowned Sword,Legendary,Warrior Pokémon,Fairy,Steel,2.8,355.0,92.0,170.0,115.0,148.0
1024,889,Zamazenta Crowned Shield,Legendary,Warrior Pokémon,Fighting,Steel,2.9,785.0,92.0,130.0,145.0,128.0
1026,890,Eternatus,Legendary,Gigantic Pokémon,Poison,Dragon,20.0,950.0,140.0,85.0,95.0,130.0

In [74]:
dt.name

0                            Bulbasaur
1                              Ivysaur
2                             Venusaur
3                        Mega Venusaur
4                           Charmander
                     ...
1023       Zacian Hero of Many Battles
1024          Zamazenta Crowned Shield
1025    Zamazenta Hero of Many Battles
1026                         Eternatus
1027               Eternatus Eternamax
Name: name, Length: 1028, dtype: object